### ISSUE TITLE
Typo in Changes section

### ISSUE THREAD

**Issue by clehner** [kemitchell/turnstiletos.com#3]
The [Changes](https://turnstiletos.com/1e#changes) section says "They operator may …". Should it instead say "The operator may ..."?

**Comment by kemitchell** [comment]
Howdy, @clehner! Long time, no see. Hope you're okay.

You're right about the typo. I will push a new release shortly.

**Comment by kemitchell** [comment]
Fixed in 1e1c: https://turnstiletos.com/1e1c

**Comment by kemitchell** [comment]
@clehner, I hope you don't mind that I thanked you by name on https://turnstiletos.com/editions.

I really appreciate you opening this issue. Especially since I know GitHub isn't your favorite.

**Comment by clehner** [comment]
@kemitchell thanks, happy to be mentioned. But there is another typo: "Lerner" should be "Lehner".

Also, should the URL in the `a` tag here be updated? https://github.com/kemitchell/turnstiletos.com/blob/main/1e1c.html#L30

It's cool to see you continuing to innovate.

**Comment by kemitchell** [comment]
@clehner, sorry about that! I've just amended commit and deployed.

If there's "innovation" here, it's all yours!
