### ISSUE TITLE
Make account creation optional

### ISSUE THREAD

**Issue by Zwyx** [kemitchell/turnstiletos.com#4]
Hi and thank you for making these terms!

In the `Your Account` part:

```
1. You must create and log into an account to use some features of the website.
```

Could it be possible to change `must` by `may need to`? This is for website that don't have any kind of user account feature.

**Comment by kemitchell** [comment]
PR?

**Comment by Zwyx** [comment]
With pleasure: https://github.com/kemitchell/turnstiletos.com/pull/5. Also, I made some even simpler terms (before I learned about yours). They might still be relevant for some people, as they are for websites with no Account Creation, no Content Sharing, and no Cookies. I'd be keen to get your opinion (at least to know if I haven't done a massive mistake). Would you be able to have [a quick read](https://github.com/Zwyx/minimal-terms-of-use-and-privacy-policy)?
